apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-test
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 1Gi
