apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-block-test
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 1Gi
